# set status bar to top
set-option -g status-position top

# improve colors and enable italic
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Add truecolor support
set-option -ga terminal-overrides ",xterm-256color:RGB"
set -ga terminal-overrides ',xterm-256color:Tc'
set -as terminal-overrides ',xterm*:sitm=\E[3m'

# Change keybinds for splitting windows
bind | split-window -h
bind - split-window -v

# Refresh tmux configuration
unbind r
bind r source-file ~/.tmux.conf

# Resize tmux panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Maximize/Minimize tmux pane
bind -r m resize-pane -Z

# Enable the mouse
set -g mouse on

# Vim movements for tmux's copy mode
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

# start window numbers at 1 to match keyboard order with tmux window order
set -g base-index 1
set-window-option -g pane-base-index 1

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# increase scrollback lines
set -g history-limit 10000

# TPM - Tmux Plugin Manager
set -g @plugin 'tmux-plugins/tmp'

# List of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl
set -g @plugin 'o0th/tmux-nova'

set -g @nova-nerdfonts true

set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 

# set -g @nova-pane-active-border-style "#fc514e" # "#44475a"
# set -g @nova-pane-border-style "#fc514e" # "#282a36"
set -g @nova-status-style-bg "#080808" # "#4c566a"
set -g @nova-status-style-fg "#acb4c2" # "#d8dee9"
set -g @nova-status-style-active-bg "#b2ceee" # "#89c0d0"
set -g @nova-status-style-active-fg "#080808" # "#2e3540"
# set -g @nova-status-style-double-bg "#fc514e" # "#2d3540"

set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

set -g @nova-segment-mode "#{?client_prefix,גּ,}"
set -g @nova-segment-mode-colors "#a1aab8 #080808" # "#78a2c1 #2e3440"

# Session Segment
set -g @nova-segment-session "#{session_name}"
set -g @nova-segment-session-colors "#21c7a8 #080808"

set -g @nova-segment-bleft-colors "#080808 #080808"
set -g @nova-segment-bright-colors "#080808 #080808"

set -g @nova-rows 0
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "session"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
