#!/bin/bash

# active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
# active_color=0xffe2e2e3 inactive_color=0xff414550 width=5.0'
# active_color=0xff89b4fa inactive_color=0xff313244

options=(
  style=round
  width=5.0
  hidpi=on
  active_color=0xff89b4fa
  inactive_color=0xff313244
)

borders "${options[@]}"
