#!/bin/sh

if [ -f "$HOME/Brewfile" ]; then
  if brew bundle --file="$HOME/Brewfile" >/dev/null 2>&1; then
    echo "Homebrew bundle installation completed successfully."
  else
    echo "Homebrew bundle failed."
  fi
fi
